# Utility function to clean up the population names and strip run timing
clean.pops=function(pops){
  pops.trim=sapply(pops, function(x){ str_split(x,"[|]")[[1]][2] } ) 
  
  pops.trim=str_replace_all(pops.trim, "Spring[/]", "")
  pops.trim=str_replace_all(pops.trim, "Rivers", "R.")
  pops.trim=str_replace_all(pops.trim, "River", "R.")
  pops.trim=str_replace_all(pops.trim, "Creeks", "Cr.")
  pops.trim=str_replace_all(pops.trim, "Creek", "Cr.")
  pops.trim=str_replace(pops.trim, "Tributaries", "Tribs.")
  run.trim=sapply(pops, function(x){ str_split(x,"[|]")[[1]][3] } )
  run.trim=str_replace(run.trim, "Fall-run", "FR")
  run.trim=str_replace(run.trim, "Spring[/]Summer-run", "SSR")
  run.trim=str_replace(run.trim, "Summer[/]Winter-run", "SWR")
  run.trim=str_replace(run.trim, "Winter-run", "WR")
  run.trim=str_replace(run.trim, "Early-run", "ER")
  run.trim=str_replace(run.trim, "Early-late-run", "ELR")
  run.trim=str_replace(run.trim, "Spring-run", "SpR")
  run.trim=str_replace(run.trim, "Summer-run", "SuR")
  run.trim=str_replace(run.trim, "Late-run", "LR")
  run.trim=str_replace(run.trim, "Late fall", "LFR")
  run.trim=str_replace(run.trim, "NA", "")
  pops.trim = paste(pops.trim, run.trim)
  pops.trim=str_replace(pops.trim, "Spring SSR", "SSR")
  pops.trim=str_replace(pops.trim, "Washington", "WA")
  pops.trim=str_replace(pops.trim, "Oregon", "OR")
  pops.trim=str_replace(pops.trim, "North Fork", "NF")
  pops.trim=str_replace(pops.trim, "North", "N.")
  pops.trim=str_replace(pops.trim, "South Fork", "SF")
  pops.trim=str_replace(pops.trim, "Middle Fork", "MF")
  pops.trim=str_replace(pops.trim, "East Fork", "EF")
  pops.trim=str_replace(pops.trim, "West Fork", "WF")
  pops.trim=str_replace(pops.trim, "South", "S.")
  pops.trim=str_replace(pops.trim, "Upper", "Up.")
  pops.trim=str_replace(pops.trim, "Lower", "Low.")
  pops.trim=str_replace(pops.trim, ", and ", "/")
  pops.trim=str_replace(pops.trim, " and ", "/")
  pops.trim=str_replace(pops.trim, ", ", "/")
  
  pops.trim=str_trim(pops.trim)
  pops.trim
}
